# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumb:
            quality: 85
            filters:
                thumbnail: { size: [538, 250], mode: outbound}
        recipeBackground:
            quality: 85
            filters:
                thumbnail: { size: [730, 250], mode: outbound}
        avatar:
            quality: 75
            filters:
                thumbnail: { size: [25, 25], mode: outbound}