vich_uploader:
    db_driver: orm

    mappings:
        recipes:
            uri_prefix: /images/recipe
            upload_destination: '%kernel.project_dir%/public/images/recipe'
        avatars:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
